# .github/workflows/docker-build-push.yml
name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      push_to_dockerhub:
        description: 'Push to Docker Hub?'
        type: boolean
        required: true
        default: false
      image_version:
        description: 'Image version tag'
        type: string
        required: true
        default: 'latest'

env:
  REGISTRY_ALIYUN: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: ${{ secrets.ALIYUN_NAME_SPACE }}/qm-music

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_ALIYUN }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build and Push to Aliyun
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_ALIYUN }}/${{ env.IMAGE_NAME }}:${{ inputs.image_version }}

      - name: Login to Docker Hub
        if: ${{ inputs.push_to_dockerhub }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ inputs.push_to_dockerhub }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ inputs.image_version }}